import { DrillCard } from '../logic/types';

/** The drill bank. Prompts are the question; keys are what a strong answer covers. */
export const DRILLS: DrillCard[] = [
  // Anthropic
  { id: 'a1', lab: 'anthropic', round: 'coding', prompt: 'Design the first ten minutes of a "coding to a spec" solution: you must dedupe LLM outputs by sentence, drop texts under 10 words, and sort by word count descending. What do you write first?', hint: 'Think about what level 2 might add.', keys: ['small pure functions per requirement', 'normalised sentence hashing for dedupe', 'stable sort with sorted() and a key', 'type hints and a tiny test', 'leave hooks for new filters'] },
  { id: 'a2', lab: 'anthropic', round: 'coding', prompt: 'Your in-memory key-value store now needs TTL expiry. How do you add it without breaking get/set, and what do you do about clock dependence in tests?', hint: 'Injected clock.', keys: ['store expiry alongside value', 'lazy expiry on read plus optional sweep', 'inject a clock function for tests', 'document behaviour at exact expiry'] },
  { id: 'a3', lab: 'anthropic', round: 'design', prompt: 'Design a distributed annotation platform for millions of texts and images with quality control.', hint: 'Metadata, blobs, hot state, agreement.', keys: ['Postgres metadata + object store blobs + Redis task state', 'task assignment and redundancy (2 to 3 labels per item)', "agreement metrics like Cohen's kappa; gold questions", 'bias monitoring and annotator calibration', 'cost per million items'] },
  { id: 'a4', lab: 'anthropic', round: 'values', prompt: 'A feature would materially help users but modestly increases misuse risk. Walk through how you would decide whether to ship it.', hint: 'Not yes or no. A process.', keys: ['quantify benefit and harm with evidence', 'mitigations and monitoring before launch', 'staged rollout with kill switch', 'who decides and what would change your mind', 'reference to responsible scaling thinking'] },
  { id: 'a5', lab: 'anthropic', round: 'values', prompt: 'Explain Constitutional AI to a strong engineer who has not read the paper. Where does it help and where does it fall short?', hint: 'Principles, critique-revise loop, RLAIF.', keys: ['a written set of principles', 'model critiques and revises its own outputs', 'preference labels from AI feedback replace some human labels', 'limits: principle quality, evaluation gaps, gaming'] },
  { id: 'a6', lab: 'anthropic', round: 'behavioral', prompt: 'Tell me about a time you slowed a launch down because something was not right.', hint: 'Cost of the delay, and what you gained.', keys: ['specific risk you saw', 'how you raised it and to whom', 'what evidence you gathered', 'outcome and what it cost', 'what you would do faster now'] },
  { id: 'a7', lab: 'anthropic', round: 'design', prompt: "Design the serving path for a chat product on a large model: requests arrive in bursts, responses stream, and some prompts are very long.", hint: 'Batching versus latency.', keys: ['admission control and queueing', 'continuous batching and KV cache memory budget', 'streaming with backpressure', 'fallback models and graceful degradation', 'SLOs in tail latency and cost per token'] },
  // OpenAI
  { id: 'o1', lab: 'openai', round: 'mlcoding', prompt: 'Write a single-head scaled dot-product attention forward pass from scratch. Annotate every tensor with its shape.', hint: 'Mask before softmax.', keys: ['Q K V projections and shapes', 'scores = QK^T / sqrt(d)', 'causal mask with -inf before softmax', 'numerically stable softmax', 'output shape and where dropout goes'] },
  { id: 'o2', lab: 'openai', round: 'mlcoding', prompt: 'Sketch a training loop with evaluation and checkpointing that can resume after a crash. What state do you save?', hint: 'Not just the weights.', keys: ['model, optimizer, scheduler, step, RNG state, data position', 'eval on a fixed subset each N steps', 'atomic checkpoint writes', 'gradient accumulation and clipping'] },
  { id: 'o3', lab: 'openai', round: 'debugging', prompt: 'Training loss is flat from step zero even though the code compiles and runs. Give your first three hypotheses and how you would test each in under ten minutes.', hint: 'Cheapest test first.', keys: ['learning rate zero or scheduler bug', 'labels misaligned or all-same', 'gradients not flowing (detach, no_grad, frozen params)', 'overfit a single batch as the canonical test'] },
  { id: 'o4', lab: 'openai', round: 'design', prompt: 'Explain KV caching, then estimate the memory for a 70B model serving 64 concurrent sequences of 8k tokens.', hint: 'layers × heads × head_dim × 2 × dtype bytes × tokens.', keys: ['cache stores K and V per layer per token', 'memory grows linearly in sequence and batch', 'a worked estimate with stated assumptions', 'paged attention or quantised cache as mitigations'] },
  { id: 'o5', lab: 'openai', round: 'research', prompt: 'Pick your best project. Explain it in one minute, then name the two ways it fails.', hint: 'Failure modes show taste.', keys: ['clear problem and metric', 'your specific contribution', 'two honest failure modes', 'what you would do next with more time'] },
  { id: 'o6', lab: 'openai', round: 'behavioral', prompt: 'Tell me about shipping something under real uncertainty. How did you decide what was good enough?', hint: 'Speed with judgment.', keys: ['what was unknown', 'the smallest thing that answered the question', 'how you set the bar', 'what happened after launch'] },
  // DeepMind
  { id: 'd1', lab: 'deepmind', round: 'quiz', prompt: 'What does the SVD of a weight matrix tell you, and how does it connect to model compression?', hint: 'Rank and energy.', keys: ['U Σ V^T, singular values as importance', 'low-rank approximation and reconstruction error', 'connection to LoRA-style adapters', 'compute cost of SVD'] },
  { id: 'd2', lab: 'deepmind', round: 'quiz', prompt: 'Forward-mode versus reverse-mode autodiff: when is each cheaper, and why does deep learning use reverse mode?', hint: 'Inputs versus outputs.', keys: ['forward cost scales with inputs, reverse with outputs', 'loss is scalar so reverse wins', 'memory cost of storing activations', 'checkpointing trade-off'] },
  { id: 'd3', lab: 'deepmind', round: 'quiz', prompt: 'Derive the MLE for the mean of a Gaussian, then explain how a prior turns it into MAP.', hint: 'Log-likelihood.', keys: ['write the log-likelihood', 'differentiate and set to zero', 'sample mean', 'MAP adds log prior; shrinkage'] },
  { id: 'd4', lab: 'deepmind', round: 'research', prompt: 'You are handed a paper the night before. Give the structure of a one-page critique.', hint: 'Lead with the strongest limitation.', keys: ['claim and contribution in two lines', 'assumptions that carry the result', 'baselines and ablations missing', 'the next experiment you would run'] },
  { id: 'd5', lab: 'deepmind', round: 'debugging', prompt: 'Validation accuracy is far better than expected on day one. What do you check?', hint: 'Leakage.', keys: ['train/val overlap and dedup', 'label leakage through features', 'eval code bug', 'a sanity baseline'] },
  // Meta / Big Tech
  { id: 'm1', lab: 'meta', round: 'design', prompt: 'Design a feed ranking system end to end: candidate generation to serving.', hint: 'Metric first.', keys: ['objective and metric', 'candidate generation, ranking, re-ranking', 'features and training data logging', 'online serving latency and A/B testing'] },
  { id: 'm2', lab: 'meta', round: 'behavioral', prompt: 'Tell me about your highest-impact project. How do you know it was the impact you claim?', hint: 'Attribution.', keys: ['metric moved and baseline', 'your role versus team', 'how impact was measured', 'what you would scale next'] },
  { id: 'b1', lab: 'bigtech', round: 'coding', prompt: 'Given intervals, merge overlapping ones. Then extend to support deleting an interval efficiently.', hint: 'Sort, then sweep.', keys: ['sort by start', 'linear merge', 'edge cases: touching intervals', 'extension: ordered structure for deletes'] },
  { id: 'b2', lab: 'bigtech', round: 'design', prompt: 'Design a rate limiter for a public API with per-user and global limits.', hint: 'Token bucket, sliding window.', keys: ['algorithm choice and trade-offs', 'distributed state in Redis with atomic ops', 'clock skew and hot keys', 'what you return to the client'] },
  { id: 'b3', lab: 'bigtech', round: 'behavioral', prompt: 'Describe a disagreement with a senior engineer. How was it resolved?', hint: 'Evidence over volume.', keys: ['the actual technical disagreement', 'how you gathered evidence', 'outcome, including if you were wrong', 'relationship afterwards'] },
  // Shared
  { id: 's1', lab: 'all', round: 'behavioral', prompt: '"Tell me about yourself" in 90 seconds, tuned for this lab.', hint: 'Present, past, why here.', keys: ['present role in one line', 'two relevant proofs from the past', 'why this lab specifically', 'under 90 seconds'] },
  { id: 's2', lab: 'all', round: 'behavioral', prompt: 'Why this company, and why now?', hint: 'Specific, not flattering.', keys: ['a specific team, paper, or product', 'how your work connects', 'what you want to learn', 'no generic mission talk'] },
  { id: 's3', lab: 'all', round: 'coding', prompt: 'Explain how you approach a coding interview problem in the first three minutes.', hint: 'Clarify, examples, plan.', keys: ['restate and clarify constraints', 'small example and edge cases', 'approach with complexity', 'agree on the plan before typing'] },
  { id: 's4', lab: 'all', round: 'design', prompt: 'Estimate storage for one year of logs for a service handling 10k requests per second at 1 KB each.', hint: 'Show the arithmetic.', keys: ['10k × 86,400 × 365 × 1KB', 'about 315 TB before compression', 'compression and retention tiers', 'state assumptions'] },
  { id: 's5', lab: 'all', round: 'behavioral', prompt: 'Tell me about a time you failed. What changed afterwards?', hint: 'Own it fully.', keys: ['a real failure with cost', 'your part without deflection', 'the concrete change in how you work', 'evidence it stuck'] },
  { id: 's6', lab: 'all', round: 'debugging', prompt: 'Your service p99 latency doubled after a deploy with no functional change. Where do you look first?', hint: 'Diff the deploy.', keys: ['diff config and dependencies', 'GC, connection pools, retries', 'dashboards: which tier moved', 'rollback criteria'] },
];
