/** One line a day. The grind is yours; this is the sign on the road. */
export const RULES: string[] = [
  'one hard problem a day beats ten easy ones a week.',
  'say the plan before you type. every round.',
  'your best project should survive five "why" questions.',
  'shapes in comments. always.',
  'the fix for nerves is reps, not confidence.',
  'read the company\'s own words before the values round.',
  'a clean level one is worth more than a rushed level three.',
  'numbers in every story: before, after, how measured.',
  'cheapest hypothesis first. always.',
  'sleep is part of the plan, not a reward.',
  'ask one clarifying question before every problem. one.',
  'the interviewer wants you to pass. help them.',
  'derive it once by hand this week.',
  'end each story with what you would do differently.',
  'you are allowed to say "I do not know, here is how I would find out."',
  'practice out loud. silent prep does not transfer.',
  'one paper, one page of critique, once a week.',
  'time-box the mock. real rounds end.',
  'referrals are earned with kindness, not asked for cold.',
  'your accent is not the problem. pace is. slow down 10 percent.',
  'recruiters remember how you treat them. so do reference checks.',
  'the goal is not to seem smart. it is to be clear.',
  'estimate before you design. every time.',
  'rest days are scheduled, not stolen.',
  'today\'s plan is the only plan that matters.',
  'tell your parents what you are doing. it helps more than you think.',
  'write the test before the fourth level.',
  'you are competing with your yesterday self, not with the forum.',
];
